import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./app.css";
import Providers from "./providers";
import LogoutButton from "../components/LogoutButton"; // Import the LogoutButton component
import { Authenticator } from '@aws-amplify/ui-react';
import { usePathname } from 'next/navigation'; // Import usePathname hook

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const pathname = usePathname(); // Get the current pathname

  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <header>
            <Authenticator>
              {({ signOut, user }) => (
                <>
                  {user && pathname !== '/login' && pathname !== '/' && (
                    <LogoutButton />
                  )}
                </>
              )}
            </Authenticator>
          </header>
          {children}
        </Providers>
      </body>
    </html>
  );
}
