// filepath: /c:/Users/TJoshi/Downloads/graphql-amp2-main/graphql-amp2-main/app/layout.tsx
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./app.css";
import Providers from "./providers";
import LogoutButton from "../components/LogoutButton"; // Import the LogoutButton component

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <header>
            <LogoutButton /> {/* Add the LogoutButton component */}
          </header>
          {children}
        </Providers>
      </body>
    </html>
  );
}
